### PR TITLE
Removing bower dependencies and managing them via Gulp and Yarn

### LINKED ISSUE #30: Drop bower
Stop using bower, in favour of yarn and webpack

Also, the gem generation scripts should continue working.

### PR DESCRIPTION
**Pull request by Javi**
Fixes #30 
Builds from now on should be managed with ``yarn``, not ``npm install``

### CODE REVIEW

**Comment by flbulgarelli** [comment]
I have heard that newer versions of npm provide a `package.json.lock`. With that in mind, does it worth the effort to switch to yarn? Can't just upgrade npm?

**Comment by flbulgarelli** [comment]
Also, just a question: is still necessary to keep the generated sources in the source control?

**Comment by Javi** [comment]
The simplest way to migrate away from bower is to switch to yarn, since unlike npm they have a specialized organization for bower packages (which may not be in the npm registry), where packages are installed from github into node_modules/@bower_components. Then you can symlink the folder into src in a postinstall script for development, as a first step to keep everything working. In this particular case, I could just change the paths to node_modules since they were few. From then on, the project can start to be rewritten in order to remove any references to bower, and its coupled cousin wiredep which is the real troublemaker, as it's an important part of the current build process and does not work without bower at all. This PR frees the repo from both of them, and allows us to start a code rewrite to implement webpack, if we wanted to.

Regarding generated sources, what's included is the scss files, I'll check out why so many were added in the dist process.

**Comment by flbulgarelli** [comment]
Ok. The Ruby gen Will continue working, right?

**Comment by Javi** [comment]
Yes, the tag script runs ``gulp dist`` and the ``Rakefile`` works with the generated dist folder, ignoring dependency management.

**Comment by flbulgarelli** [comment]
Ok!

> Regarding generated sources, what's included is the scss files, I'll check out why so many were added in the dist process.

Please focus on this. We should not add ~20K lines of code to the repository without a good reason :smile:

**Comment by fedescarpa** [comment]
Is this branch ready to merge into master?

**Comment by Javi** [comment]
Ok, so now the unused dependencies are removed via a Sass tree shaking, it turned out yarn was ignoring the 'ignore' field from bower and that's where all of the dependency sources came from.

The shaking tool failed in window so I had to fork it and fix it, so since this is a large build change across environments, could you try building it in your machine to check it works as intended? If it does then it should be ready.

**Comment by fedescarpa** [comment]
It work fine locally... merging :crossed_fingers:

**Pull request merged**
