### PR TITLE
New mumuki-styles

### PR DESCRIPTION
**Pull request by felipecalvo**
# :paintbrush: New mumuki-styles

This PR aims for a 3.0.0 release which breaks all kinds of compatibility with older versions. There are two objectives:

## Improve, fix and cleanup dev-related stuff

This includes:

* Rewrite README
* Remove very old references to bower stuff
* Delete redundant code on gulpfile
* Dependencies cleanup/update
* Improve yarn tasks
* Ignore dist folder while developing and unignore when tagging. The implementation is a bit dodgy - you might want to look at [this commit](https://github.com/mumuki/mumuki-styles/commit/288b05c887df567bd75d62cab1375615f2a786bc) in disapproval, but it does almost completely eliminate the modified dist files cluttering when developing (except for newly generated ones, since they're not in the repo yet).

## Upgrade to Bootstrap 5

This is the biggest change, upgrading from Boostrap 3.3.7. This doesn't introduce too many changes on this repository but it does imply a lot of work for apps which depend on mumuki-laboratory. I already covered the reasons for upgrading elsewhere but after dealing with pre-4.0 code for so long I wanted a more up to date experience. First, it has native SASS suport and has almost every setting on a variable we can override much more easily than before. And then it gives us many more classes, elements and utilities to work with, an infinitely more complete documentation, accesibility concerns which were almost nil on 3.3.7, and it's a good time to update - 5.0.0 is just about to release.

This PR uses Bootstrap 5.0.0-beta3. I was a little bit scared of the word beta - I initally started work when it was on beta 1 - but [the amount of changes from beta2 to beta3 was very, very small](https://getbootstrap.com/docs/5.0/migration/#v500-beta3), and [the next release will actually be stable 5.0.0](https://blog.getbootstrap.com/2021/03/23/bootstrap-5-beta-3/). After tens of hours of developing and testing on laboratory I haven't found any bug or anything strange, but we can wait for the stable release if depending on a beta makes you uncomfortable.

There are lot of commits here, so I'll cover a few of the most important points over individual comments so we can have a little discussion on each subject if we desire.

### CODE REVIEW

**Comment by felipecalvo** [comment]
## Reverted changes

I've overridden some of the decisions in Bootstrap 5 as to minimize the amount of changes in our current views. For example, they decided that all links will be underlined by default - except for those in elements such as dropdowns - which didn't look very good on our apps.

image
_____
They also dropped most of the styles for blockquotes, pre and code elements, which resulted in uglier views.
_____
image

image
_____

These are one of the few cases when upgrading was a bit inconvenient as I had to actually _add_ code instead of remove, but the styles are relatively simple and shouldn't have to be modified again.

Something similar happened with forms:

_____
image
_____

Again, I reverted this by making the labels bold and adding some padding between fields as we're used to.

**Comment by felipecalvo** [comment]
## HTML, body and footer tags

I fixed a very insignificant bug we've had since forever - no matter how empty a view was, there was _always_ a little bit of scrolling to do.

____

Screenshot from 2021-04-04 13-35-34

____

This required very simple styling for the HTML, body and footer tags. I added those here so every app can benefit from it.

**Comment by felipecalvo** [comment]
## Colors

The `_colors.scss` files is now structured as follows:

### 1. Bootswatch variables import

This loads the variables used by our theme, Flatly, so we can override them. We do as such:

1a. Override standard colors (primary, secondary, success, info, warning and danger) so our colors take priority over Bootswatch's and Bootstrap's
1b. Add our own main colors (complementary [pink] and broken [dark red])
1c. Other Bootswatch variables to override. For example, Flatly decides that their pagination styles should have X color but we want it pink, so we override those.

### 2. Bootstrap utilities import

This loads a few basic Bootstrap files, such as variables and a few functions they use to calculate them. Here we do as such:

2a. Add our own custom colors, complementary and broken, to their `$theme-colors` map so they're taken into account by Bootstrap. For example, pink and dark red buttons are automatically added on compilation through `btn-complementary` and `btn-broken` classes, as well as other elements.

2b. Other Bootstrap variables we want to override, such as input, table and form colors, and some pagination extra ones. These are variables where Bootswatch had no saying - we're overriding Bootstrap directly.

2c. More custom colors. Mostly legacy stuff that should be cleaned up later, as I'm sure most are redundant, not used, or used only once.

Full Bootstrap is loaded on the imports file as a final step. This is the correct order for every variable to be overridden as it should.

As future work I'd like to see if we can remove Bootswatch/Flatly entirely. I didn't want to add more complexity to this PR, but it makes the import order very messy, we're not even making use of its six main colors and there are so many variables we override already! We can probably do with Bootstrap alone now that its SASS-based approach makes it so easy to customize.

**Review by luchotc — APPROVED** [review]
This is without a doubt one of the best documented, complete, useful and organized PR I've ever reviewed. There are a lot of things happening here but they are so well explained that it was actually fun to review. Congratulations for that @felipecalvo :clap: :heart: 

Apart from that I think it's spotless. I could not find a single change that made me frown.

The solution with update-index is not ideal, but it's better that what we currently have, and we've already attempted to improve it (and in fact we did), so let's add it as well.

:100:000!

PS: I'm adding @fedescarpa as a reviewer as well, just in case I'm missing something

**Comment by felipecalvo** [comment]
Thank you for your kind words :heart: I'm glad it was not a chore to do the review.

**Review by fedescarpa — APPROVED** [review]

**Pull request merged**
